### ISSUE TITLE
A quick question about accessing the slide-seqv2 data with spliced/unspliced information

### ISSUE THREAD

**Issue by HelloWorldLTY** [welch-lab/cytosignal#1]
Great work! I have a quick question here. I wonder if you have plan to release your data for rna velocity inference of Setero-seq data:

![image](https://github.com/welch-lab/cytosignal/assets/43333475/2eb2d6ea-f2cd-47a3-8973-cd996bf42c73)

Since they did not offer versions of their workflow, and we cannot find the bam file, it will be really helpful if you plan to release this dataset. Thanks a lot!

**Comment by skpalan** [comment]
Hi, thanks for your interests! Yes we will release these data soon! Stay tuned!
