### ISSUE TITLE
How should I import 10X data?

### ISSUE THREAD

**Issue by GG7373** [welch-lab/cytosignal#2]
Great work! I have a quick question here,How should I import 10X data?

**Comment by skpalan** [comment]
Hi, you can just provide: 1) cell x gene matrix 2) cell spatial coordinates, and 3) a conversion ratio between micron and pixels. Then you could refer to our [tutorial](https://htmlpreview.github.io/?https://github.com/welch-lab/cytosignal/blob/master/doc/cytosignal.html) and follow the standard pipeline.
