### ISSUE TITLE
 What is the conversion ratio for the 10x Visium data?

### ISSUE THREAD

**Issue by OceanYangLiu** [welch-lab/cytosignal#3]
It's an amazing software!! I want to ask what is the conversion ratio for the 10x Visium data?

**Comment by skpalan** [comment]
Thank you for your interest! The conversion rate kind of depends on the specific visium data you're working with. For the most accurate results, you could calculate the rate by: `width of the capture area (in µm)/ max(pxl_col_in_fullres)-min(pxl_col_in_fullres) (in pixels)`. For the visium dataset (11 mm capture area) we used in the manuscript, we used a conversion rate of `1 pixel ≈ 0.274 µm`.

**Comment by OceanYangLiu** [comment]
Thank you for your response, it was really helpful to me!
