### ISSUE TITLE
Visium clarification for contact dependent interactions

### ISSUE THREAD

**Issue by inofechm** [welch-lab/cytosignal#5]
Hello I am interested in analyzing the contact dependent interactions in Visium data.

Does the cytosignal code automatically account for only looking at expression within each spot and not regarding directly proximal spots as is described in the manuscript:

> For contact-dependent interactions, because cells will only touch their directly connected cells within the same spot, we only need to consider gene expression within each spot without applying spatial smoothing across spots (Fig. 5f).

 or do I need to tweak any parameters to ensure it only focuses on the expression within spots?

Thank you

**Comment by skpalan** [comment]
It seems we miss this use cae when packaging everything up. An update with corresponding support will come up very soon!

**Comment by mvfki** [comment]
Hi @inofechm 

We've updated the repository. Now the code guided by the [tutorial](https://htmlpreview.github.io/?https://github.com/welch-lab/cytosignal/blob/master/doc/cytosignal.html) (primarily in function `inferIntrScore ()`) automatically accounts for the within-spot contact-dependent interactions. The related description is also added to its [related section](https://htmlpreview.github.io/?https://github.com/welch-lab/cytosignal/blob/master/doc/cytosignal.html#calculating-ligand-receptor-co-expression-and-identifying-spatially-significant-interactions) in the tutorial.

**Comment by inofechm** [comment]
thanks will try it out in the future!
