### ISSUE TITLE
cs <- findNN(cs) is generating error

### ISSUE THREAD

**Issue by anne04** [welch-lab/cytosignal#6]
findNN(cs) is generating error when I am executing the tutorial from this site: https://htmlpreview.github.io/?https://github.com/welch-lab/cytosignal/blob/master/doc/cytosignal.html

The screenshot is provided below:

![Screenshot from 2024-04-23 16-18-14](https://github.com/welch-lab/cytosignal/assets/16518375/f789c5f8-eb1e-40bd-bc04-a1199b2b6efc)

**Comment by skpalan** [comment]
Thanks for your interest. However, I was not able to reproduce the error with our demo data. Which platform are you using?

**Comment by anne04** [comment]
I am using CentOS Linux.

**Comment by mvfki** [comment]
@anne04 Did you run the [Preprocessing](https://htmlpreview.github.io/?https://github.com/welch-lab/cytosignal/blob/master/doc/cytosignal.html#preprocessing) steps? The scale factor is internally pre-computed during `removeLowQuality()` and I can see the same error message if I skip that code chunk.

**Comment by anne04** [comment]
Thank you! You are right, I was skipping the preprocessing. It was a mistake on my end. Sorry to bother you. After doing that everything is working.

**Comment by mvfki** [comment]
All good! Although those are steps not supposed to be skipped, we will try to optimize the workflow a bit to see if such errors can be eliminated.
