### ISSUE TITLE
scale.factor for Visium data

### ISSUE THREAD

**Issue by anne04** [welch-lab/cytosignal#8]
Hi, 
There is a line where you set the scale factor as below:
cs <- inferEpsParams(cs, scale.factor = 0.73)

What should be the scale.factor for Visium data, where the contents of scalefactors_json.json file are as below:
{"tissue_hires_scalef": 0.17011142,
 "tissue_lowres_scalef": 0.051033426",
 "fiducial_diameter_fullres": 144.4773339857,
 "spot_diameter_fullres": 89.43834961021503}

Thanks,
Fatema

**Comment by skpalan** [comment]
Hi! Please refer to our previous reply here: https://github.com/welch-lab/cytosignal/issues/3#issuecomment-2027641192
