### ISSUE TITLE
I wonder how to plot the circos plot using interaction data

### ISSUE THREAD

**Issue by Shuting-Zhao** [welch-lab/cytosignal#9]
Hi, I wonder how to plot the circos plot (just like the ones in your paper) ? 
I failed to find the exact cell-cell pairs info from the CytoSignal object in order to plot circos plot

![image](https://github.com/welch-lab/cytosignal/assets/125958792/6a239a11-aa5e-4a28-be79-dafe474606d5)

**Comment by skpalan** [comment]
Hi Shuting, we definitely plan to include the circos plots as a built-in plotting function in the CytoSignal package but haven't had the time to do so yet. We will add it soon. If you could email me, I can share some scripts for generating this plot. Thanks!
